spring:
  application:
    name: "booking"
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database: postgresql
  datasource:
    url: jdbc:postgresql://ec2-54-157-16-196.compute-1.amazonaws.com/d70bt103r42qil
    username: gfqchydbarkdgg
    password: ade73d550e704c6bfe32b189127e9b85cb51964f6db389adedda4869339f60b7
  jackson:
    default-property-inclusion: non_null
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
---
logging:
  level:
    root: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE
---
authTokenFilter:
  enabled: false
