spring:
  application:
    name: "booking"
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
  datasource:
    url: jdbc:postgresql://localhost:5432/booking
    username: postgres
    password: "icbqo264848"
  jackson:
    default-property-inclusion: non_null
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
---
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE
---
authTokenFilter:
  enabled: false
