spring:
  application:
    name: "project-web-application"
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/booking
    username: postgres
    password: "${Password}"
